import Head from "next/head";

import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import Experiense from "../components/Experiense";
import Skills from "../components/Skills";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div className="bg-[#080714] snap-y snap-mandatory h-screen overflow-y-scroll lg:p-8 scroll-smooth overflow-x-hidden">
      <Head>
        <title>Alireza Portfolio</title>
        <meta name="description" content="Generated by Alireza Barkhordari" />
      </Head>

      {/* {Header} */}
      <Header />

      {/* {Hero Section} */}
      <section className="snap-start">
        <Hero />
      </section>

      {/* {About Section} */}
      <section className="snap-center">
        <About />
      </section>

      {/* {Experiences Section} */}
      <section className="snap-center">
        <Experiense />
      </section>

      {/* {Skills Section} */}
      <section className="snap-center">
        <Skills />
      </section>

      {/* {Contact Section} */}
      <section className="snap-center">
        <Contact />
      </section>
    </div>
  );
}
